### ISSUE TITLE
Milestone 3: Users can use barcode scanner for getting nutrient information

### ISSUE THREAD

**Issue by shanetzulinho** [shanetzulinho/mycatsfitness#11]
# Users can use a barcode scanner for getting nutrient information

#### Subtasks
- [ ] check barcode scanner API
- [ ] create a scanner UI
- [ ] create a database of food information
- [ ] setup Node.js for back-end
