### ISSUE TITLE
#Milestone 1: Users can input data of a cat’s information

### ISSUE THREAD

**Issue by shanetzulinho** [shanetzulinho/mycatsfitness#2]
#Milestone 1: Users can input data of a cat’s information

-  Create a page UI. (Body weights, activity level, status(normal, overweight, underweight)

#### SUBTASKS
 - [ ] linter (eslint) / prettier
 - [x] github init
 - [x] create-react-app setup
 - [x] form ([Materiul UI 5](https://mui.com/material-ui/react-text-field/)) (dont’ do validation first)
 - [ ] form validation (in the end)

_Originally posted by @shanetzulinho in https://github.com/shanetzulinho/mycatsfitness/issues/1#issuecomment-1194089700_
